server:
  port: 8004

spring:
  application:
    name: ecommerce-app
  #Primary datasource with read and write support
  datasource:
    url: jdbc:mysql://localhost:3306/ecommercedb?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 600000
