server:
  port: 8004

spring:
  application:
    name: ecommerce-app
  #Primary datasource with read and write support
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ecommercedb?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    driver-class: com.mysql.cj.jdbc.Driver
